<a href="https://colab.research.google.com/github/Carlos-A-Palomares/mis433/blob/main/Data_manipuation_flights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation in Pandas

In this assignment, you will be working on the same dataframe of flights departing New York City in 2013.

In [8]:
import pandas as pd

In [6]:
# Install the package 'nycflights13' before you can run this
from nycflights13 import flights
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

In [7]:
flights.shape

(336776, 19)

## Data frame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [9]:
# use describe() to summarize all columns
flights.describe(include='all')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
count,336776.0,336776.000000,336776.000000,328521.000000,336776.000000,328521.000000,328063.000000,336776.000000,327346.000000,336776,336776.000000,334264,336776,336776,327346.000000,336776.000000,336776.000000,336776.000000,336776
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,4043,3,105,NaN,NaN,NaN,NaN,6936
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA,NaN,N725MQ,EWR,ORD,NaN,NaN,NaN,NaN,2013-09-13T12:00:00Z
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58665,NaN,575,120835,17283,NaN,NaN,NaN,NaN,94
mean,2013.0,6.548510,15.710787,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,NaN,1971.923620,NaN,NaN,NaN,150.686460,1039.912604,13.180247,26.230100,NaN
std,0.0,3.414457,8.768607,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,NaN,1632.471938,NaN,NaN,NaN,93.688305,733.233033,4.661316,19.300846,NaN
min,2013.0,1.000000,1.000000,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,NaN,1.000000,NaN,NaN,NaN,20.000000,17.000000,1.000000,0.000000,NaN
25%,2013.0,4.000000,8.000000,907.000000,906.000000,-5.000000,1104.000000,1124.000000,-17.000000,NaN,553.000000,NaN,NaN,NaN,82.000000,502.000000,9.000000,8.000000,NaN
50%,2013.0,7.000000,16.000000,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,NaN,1496.000000,NaN,NaN,NaN,129.000000,872.000000,13.000000,29.000000,NaN
75%,2013.0,10.000000,23.000000,1744.000000,1729.000000,11.000000,1940.000000,1945.000000,14.000000,NaN,3465.000000,NaN,NaN,NaN,192.000000,1389.000000,17.000000,44.000000,NaN
max,2013.0,12.000000,31.000000,2400.000000,2359.000000,1301.000000,2400.000000,2359.000000,1272.000000,NaN,8500.000000,NaN,NaN,NaN,695.000000,4983.000000,23.000000,59.000000,NaN

## Question 1. Selecting rows

From the 'flights' dataframe, find all flights that satisfy the following certain conditions:

In [10]:
# Had an arrival delay of two or more hours
flights.arr_delay >= 2

0          True
1          True
2          True
3         False
4         False
          ...
336771    False
336772    False
336773    False
336774    False
336775    False
Name: arr_delay, Length: 336776, dtype: bool

In [11]:
# Flew to Houston (IAH or HOU)
flights.dest.isin(['IAH','HOU'])

0          True
1          True
2         False
3         False
4         False
          ...
336771    False
336772    False
336773    False
336774    False
336775    False
Name: dest, Length: 336776, dtype: bool

In [12]:
# Were operated by United (UA), American (AA), or Delta (DL)
flights.carrier.isin(['UA','AA','DL'])

0          True
1          True
2          True
3         False
4          True
          ...
336771    False
336772    False
336773    False
336774    False
336775    False
Name: carrier, Length: 336776, dtype: bool

In [13]:
# Departed in July, August, and September
flights.month.isin([7,8,9])

0         False
1         False
2         False
3         False
4         False
          ...
336771     True
336772     True
336773     True
336774     True
336775     True
Name: month, Length: 336776, dtype: bool

In [14]:
# Arrived more than two hours late, but didn’t leave late
flights[(flights.arr_delay > 120) & (flights.dep_delay < 0)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
22911,2013,1,27,1419.0,1420,-1.0,1754.0,1550,124.0,MQ,3728,N1EAMQ,EWR,ORD,135.0,719,14,20,2013-01-27T19:00:00Z
33019,2013,10,7,1357.0,1359,-2.0,1858.0,1654,124.0,AA,1151,N3CMAA,LGA,DFW,192.0,1389,13,59,2013-10-07T17:00:00Z
41075,2013,10,16,657.0,700,-3.0,1258.0,1056,122.0,B6,3,N703JB,JFK,SJU,225.0,1598,7,0,2013-10-16T11:00:00Z
55985,2013,11,1,658.0,700,-2.0,1329.0,1015,194.0,VX,399,N629VA,JFK,LAX,336.0,2475,7,0,2013-11-01T11:00:00Z
152766,2013,3,18,1844.0,1847,-3.0,39.0,2219,140.0,UA,389,N560UA,JFK,SFO,386.0,2586,18,47,2013-03-18T22:00:00Z
180893,2013,4,17,1635.0,1640,-5.0,2049.0,1845,124.0,MQ,4540,N721MQ,LGA,DTW,130.0,502,16,40,2013-04-17T20:00:00Z
181270,2013,4,18,558.0,600,-2.0,1149.0,850,179.0,AA,707,N3EXAA,LGA,DFW,234.0,1389,6,0,2013-04-18T10:00:00Z
181327,2013,4,18,655.0,700,-5.0,1213.0,950,143.0,AA,2083,N565AA,EWR,DFW,230.0,1372,7,0,2013-04-18T11:00:00Z
213693,2013,5,22,1827.0,1830,-3.0,2217.0,2010,127.0,MQ,4674,N518MQ,LGA,CLE,90.0,419,18,30,2013-05-22T22:00:00Z
226434,2013,6,5,1604.0,1615,-11.0,2041.0,1840,121.0,MQ,4657,N510MQ,LGA,ATL,158.0,762,16,15,2013-06-05T20:00:00Z
235033,2013,6,14,1708.0,1710,-2.0,2227.0,2015,132.0,AA,181,N320AA,JFK,LAX,334.0,2475,17,10,2013-06-14T21:00:00Z
244329,2013,6,24,1602.0,1605,-3.0,2134.0,1916,138.0,DL,706,N3768,JFK,AUS,247.0,1521,16,5,2013-06-24T20:00:00Z
247568,2013,6,27,2052.0,2100,-8.0,13.0,2210,123.0,US,2144,N952UW,LGA,BOS,46.0,184,21,0,2013-06-28T01:00:00Z
249957,2013,6,30,1423.0,1425,-2.0,1816.0,1554,142.0,B6,2402,N206JB,JFK,BUF,80.0,301,14,25,2013-06-30T18:00:00Z
256340,2013,7,7,1659.0,1700,-1.0,2050.0,1823,147.0,US,2183,N948UW,LGA,DCA,64.0,214,17,0,2013-07-07T21:00:00Z
256358,2013,7,7,1727.0,1730,-3.0,2203.0,1951,132.0,F9,837,N263AV,LGA,DEN,236.0,1620,17,30,2013-07-07T21:00:00Z
256373,2013,7,7,1746.0,1755,-9.0,2133.0,1921,132.0,B6,1407,N374JB,JFK,IAD,78.0,228,17,55,2013-07-07T21:00:00Z
256405,2013,7,7,1823.0,1830,-7.0,2201.0,1955,126.0,MQ,3486,N724MQ,LGA,BNA,113.0,764,18,30,2013-07-07T22:00:00Z
270742,2013,7,22,1555.0,1600,-5.0,2139.0,1938,121.0,DL,141,N713TW,JFK,SFO,371.0,2586,16,0,2013-07-22T20:00:00Z
270752,2013,7,22,1606.0,1615,-9.0,2056.0,1831,145.0,DL,1619,N970DL,LGA,MSP,140.0,1020,16,15,2013-07-22T20:00:00Z
270762,2013,7,22,1628.0,1630,-2.0,2151.0,1939,132.0,B6,423,N625JB,JFK,LAX,332.0,2475,16,30,2013-07-22T20:00:00Z
276564,2013,7,28,1710.0,1711,-1.0,2248.0,2039,129.0,B6,167,N510JB,JFK,OAK,353.0,2576,17,11,2013-07-28T21:00:00Z
287148,2013,8,8,1457.0,1500,-3.0,1828.0,1624,124.0,US,2185,N746UW,LGA,DCA,70.0,214,15,0,2013-08-08T19:00:00Z
291439,2013,8,13,657.0,659,-2.0,1015.0,814,121.0,EV,4522,N14188,EWR,BNA,146.0,748,6,59,2013-08-13T10:00:00Z
305985,2013,8,28,1157.0,1200,-3.0,1520.0,1316,124.0,US,2179,N737US,LGA,DCA,63.0,214,12,0,2013-08-28T16:00:00Z
325764,2013,9,19,656.0,700,-4.0,1037.0,833,124.0,UA,331,N808UA,LGA,ORD,192.0,733,7,0,2013-09-19T11:00:00Z

In [15]:
# Were delayed by at least an hour, but made up over 30 minutes in flight
flights[(flights.arr_delay - flights.dep_delay) >= 60]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
498,2013,1,1,1549.0,1445,64.0,1912.0,1656,136.0,EV,4181,N21197,EWR,MCI,234.0,1092,14,45,2013-01-01T19:00:00Z
609,2013,1,1,1732.0,1630,62.0,2028.0,1825,123.0,EV,4092,N16911,EWR,DAY,119.0,533,16,30,2013-01-01T21:00:00Z
834,2013,1,1,2343.0,1724,379.0,314.0,1938,456.0,EV,4321,N21197,EWR,MCI,222.0,1092,17,24,2013-01-01T22:00:00Z
1041,2013,1,2,841.0,845,-4.0,1134.0,1024,70.0,9E,3754,N829AY,JFK,BUF,59.0,301,8,45,2013-01-02T13:00:00Z
1424,2013,1,2,1558.0,1600,-2.0,1923.0,1820,63.0,MQ,3985,N627MQ,JFK,CVG,118.0,589,16,0,2013-01-02T21:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328822,2013,9,22,1449.0,1455,-6.0,1731.0,1630,61.0,MQ,3231,N682MQ,JFK,PIT,65.0,340,14,55,2013-09-22T18:00:00Z
328874,2013,9,22,1529.0,1530,-1.0,2000.0,1853,67.0,DL,141,N702TW,JFK,SFO,357.0,2586,15,30,2013-09-22T19:00:00Z
328907,2013,9,22,1556.0,1535,21.0,2011.0,1816,115.0,DL,1773,N3734B,JFK,LAS,300.0,2248,15,35,2013-09-22T19:00:00Z
328910,2013,9,22,1557.0,1600,-3.0,1930.0,1825,65.0,9E,3347,N604LR,JFK,DTW,85.0,509,16,0,2013-09-22T20:00:00Z
332198,2013,9,26,541.0,550,-9.0,1104.0,932,92.0,B6,939,N563JB,JFK,BQN,214.0,1576,5,50,2013-09-26T09:00:00Z

In [16]:
# Departed between midnight and 6am (inclusive)
flights[(flights.dep_time >= 0) & (flights.dep_time <= 600)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335802,2013,9,30,557.0,600,-3.0,852.0,923,-31.0,UA,303,N510UA,JFK,SFO,326.0,2586,6,0,2013-09-30T10:00:00Z
335803,2013,9,30,558.0,600,-2.0,815.0,829,-14.0,EV,4137,N16981,EWR,ATL,107.0,746,6,0,2013-09-30T10:00:00Z
335804,2013,9,30,558.0,600,-2.0,742.0,749,-7.0,DL,731,N337NB,LGA,DTW,83.0,502,6,0,2013-09-30T10:00:00Z
335805,2013,9,30,559.0,600,-1.0,NaN,715,NaN,WN,464,N411WN,EWR,MDW,NaN,711,6,0,2013-09-30T10:00:00Z
335806,2013,9,30,600.0,600,0.0,844.0,856,-12.0,B6,601,N588JB,JFK,FLL,139.0,1069,6,0,2013-09-30T10:00:00Z

In [17]:
# How many flights have a missing dep_time?
flights.dep_time.isna().sum()

np.int64(8255)

## Question 2. Sorting

In [18]:
# Sort flights to find the least delayed flights. Find the flights that left earliest.
flights.sort_values('dep_delay', ascending=False)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
7072,2013,1,9,641.0,900,1301.0,1242.0,1530,1272.0,HA,51,N384HA,JFK,HNL,640.0,4983,9,0,2013-01-09T14:00:00Z
235778,2013,6,15,1432.0,1935,1137.0,1607.0,2120,1127.0,MQ,3535,N504MQ,JFK,CMH,74.0,483,19,35,2013-06-15T23:00:00Z
8239,2013,1,10,1121.0,1635,1126.0,1239.0,1810,1109.0,MQ,3695,N517MQ,EWR,ORD,111.0,719,16,35,2013-01-10T21:00:00Z
327043,2013,9,20,1139.0,1845,1014.0,1457.0,2210,1007.0,AA,177,N338AA,JFK,SFO,354.0,2586,18,45,2013-09-20T22:00:00Z
270376,2013,7,22,845.0,1600,1005.0,1044.0,1815,989.0,MQ,3075,N665MQ,JFK,CVG,96.0,589,16,0,2013-07-22T20:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

In [19]:
# Which flights travelled the farthest? Which travelled the shortest?
flights.sort_values('distance', ascending=False)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
118311,2013,2,9,1206.0,900,186.0,1814.0,1540,154.0,HA,51,N380HA,JFK,HNL,645.0,4983,9,0,2013-02-09T14:00:00Z
227103,2013,6,6,1044.0,1000,44.0,1441.0,1435,6.0,HA,51,N384HA,JFK,HNL,580.0,4983,10,0,2013-06-06T14:00:00Z
224146,2013,6,3,957.0,1000,-3.0,1432.0,1435,-3.0,HA,51,N381HA,JFK,HNL,605.0,4983,10,0,2013-06-03T14:00:00Z
170226,2013,4,6,957.0,1000,-3.0,1510.0,1510,0.0,HA,51,N382HA,JFK,HNL,638.0,4983,10,0,2013-04-06T14:00:00Z
130088,2013,2,22,857.0,900,-3.0,1436.0,1540,-64.0,HA,51,N382HA,JFK,HNL,606.0,4983,9,0,2013-02-22T14:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115505,2013,2,5,2136.0,2130,6.0,2238.0,2225,13.0,EV,4619,N26141,EWR,PHL,31.0,80,21,30,2013-02-06T02:00:00Z
25145,2013,1,29,2131.0,2130,1.0,2221.0,2225,-4.0,EV,4619,N13538,EWR,PHL,25.0,80,21,30,2013-01-30T02:00:00Z
170692,2013,4,6,1948.0,1950,-2.0,2034.0,2044,-10.0,EV,4457,N29917,EWR,PHL,25.0,80,19,50,2013-04-06T23:00:00Z
112694,2013,2,2,1610.0,1617,-7.0,1702.0,1722,-20.0,EV,4616,N18120,EWR,PHL,33.0,80,16,17,2013-02-02T21:00:00Z
275945,2013,7,27,NaN,106,NaN,NaN,245,NaN,US,1632,NaN,EWR,LGA,NaN,17,1,6,2013-07-27T05:00:00Z

## Question 3. Selecting Columns

Use at least three ways to select dep_time, dep_delay, arr_time, and arr_delay from flights.

In [20]:
# Method 1
flights.loc[:,['dep_time','dep_delay','arr_time','arr_delay']]

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [21]:
# Method 2
flights[['dep_time','dep_delay','arr_time','arr_delay']]

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [22]:
# Method 3
flights.iloc[:,[3,4,6,7]]

        dep_time  sched_dep_time  arr_time  sched_arr_time
0          517.0             515     830.0             819
1          533.0             529     850.0             830
2          542.0             540     923.0             850
3          544.0             545    1004.0            1022
4          554.0             600     812.0             837
...          ...             ...       ...             ...
336771       NaN            1455       NaN            1634
336772       NaN            2200       NaN            2312
336773       NaN            1210       NaN            1330
336774       NaN            1159       NaN            1344
336775       NaN             840       NaN            1020

[336776 rows x 4 columns]

## Question 4. Adding new columns

Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers.

For example, 759 means 7:59 and 801 means 8:01. Their difference is not 42 but 2 minutes.

In [23]:
# Convert them to a more convenient representation of number of minutes since midnight (0).
flights['dep_time'] = pd.to_datetime(flights['dep_time'], format='%H%M', errors='coerce')

In [24]:
# Create a new column of arr_time - dep_time.
flights['dep_time'] = pd.to_datetime(flights['dep_time'], format='%H%M', errors='coerce')

# Compare this column with air_time.
flights['air_time']

0         227.0
1         227.0
2         160.0
3         183.0
4         116.0
          ...
336771      NaN
336772      NaN
336773      NaN
336774      NaN
336775      NaN
Name: air_time, Length: 336776, dtype: float64

In [26]:
# Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
# Try creating a column to calculate dep_delay from dep_time and sched_dep_time (and/or other columns if necessary).
flights['sched_dep_time_dt'] = pd.to_datetime(
    flights['sched_dep_time'].astype(str).str.zfill(4),
    format='%H%M',
    errors='coerce'
)


flights['calculated_dep_delay'] = (flights['dep_time'] - flights['sched_dep_time_dt']).dt.total_seconds() / 60

print("Comparison of original and calculated departure delays (first 5 rows):")
comparison_df = flights[['dep_time', 'sched_dep_time', 'sched_dep_time_dt', 'dep_delay', 'calculated_dep_delay']].head()
print(comparison_df)

Comparison of original and calculated departure delays (first 5 rows):
             dep_time  sched_dep_time   sched_dep_time_dt  dep_delay  \
0 1900-01-01 05:17:00             515 1900-01-01 05:15:00        2.0
1 1900-01-01 05:33:00             529 1900-01-01 05:29:00        4.0
2 1900-01-01 05:42:00             540 1900-01-01 05:40:00        2.0
3 1900-01-01 05:44:00             545 1900-01-01 05:45:00       -1.0
4 1900-01-01 05:54:00             600 1900-01-01 06:00:00       -6.0

   calculated_dep_delay
0                   2.0
1                   4.0
2                   2.0
3                  -1.0
4                  -6.0

## Question 5. Mixing things together

The following questions may require multiple operations above.

In [28]:
# Find the 20 most delayed flights.
# Display the following: year,month,day,carrier,flight,dep_delay,arr_delay

flights.sort_values(by='dep_delay', ascending=False).head(20)[['year', 'month', 'day', 'carrier', 'flight', 'dep_delay', 'arr_delay']]

        year  month  day carrier  flight  dep_delay  arr_delay
7072    2013      1    9      HA      51     1301.0     1272.0
235778  2013      6   15      MQ    3535     1137.0     1127.0
8239    2013      1   10      MQ    3695     1126.0     1109.0
327043  2013      9   20      AA     177     1014.0     1007.0
270376  2013      7   22      MQ    3075     1005.0      989.0
173992  2013      4   10      DL    2391      960.0      931.0
151974  2013      3   17      DL    2119      911.0      915.0
247040  2013      6   27      DL    2007      899.0      850.0
270987  2013      7   22      DL    2047      898.0      895.0
87238   2013     12    5      AA     172      896.0      878.0
195711  2013      5    3      MQ    3744      878.0      875.0
151     2013      1    1      MQ    3944      853.0      851.0
210174  2013      5   19      AA     257      853.0      852.0
119784  2013      2   10      F9     835      853.0      834.0
99938   2013     12   19      DL    1223      849.0      847.0
98014   2013     12   17      AA     172      845.0      846.0
95530   2013     12   14      DL    2391      825.0      856.0
182478  2013      4   19      DL    1435      812.0      821.0
246911  2013      6   27      AA    2019      803.0      802.0
152312  2013      3   18      DL    2363      800.0      784.0

In [31]:
# Sort all AA flights to find the top 10 fastest (highest speed) flights.
# Display the following: year,month,day,carrier,flight,orig,dest,distance,air_time,speed (miles per hour)

flights['speed'] = (flights['distance'] / flights['air_time']) * 60

flights[flights['carrier'] == 'AA'].sort_values(by='speed', ascending=False).head(10)[['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'distance', 'air_time', 'speed']]

,year,month,day,carrier,flight,origin,dest,distance,air_time,speed
70704,2013,11,17,AA,936,JFK,STT,1623,175.0,556.457143
87723,2013,12,5,AA,1029,JFK,SJU,1598,173.0,554.219653
119700,2013,2,10,AA,1613,JFK,SJU,1598,173.0,554.219653
129686,2013,2,21,AA,1613,JFK,SJU,1598,174.0,551.034483
87575,2013,12,5,AA,95,JFK,SJU,1598,175.0,547.885714
144408,2013,3,9,AA,1613,JFK,SJU,1598,176.0,544.772727
70721,2013,11,17,AA,1357,JFK,SJU,1598,176.0,544.772727
70335,2013,11,16,AA,95,JFK,SJU,1598,177.0,541.694915
119477,2013,2,10,AA,1635,JFK,SJU,1598,177.0,541.694915
119894,2013,2,11,AA,413,JFK,SJU,1598,177.0,541.694915

In [32]:
# Find all flights that satisfy the following:
# - From John F. Kennedy Airpot (JFK) or Newark Aiport (EWR) to Seattle-Tacoma Airport (SEA)
# - Carrier is UA, AA, or DL.
# - Dates from 4/1/2013 (inclusive) to 4/3/2013 (inclusive)
# - Scheduled arrival time is before noon.
# - Display the following: year,month,day,carrier,flight,origin,dest,sched_dep_time,sched_arr_time
# - Sort by year, month, day, sched_arr_time

filtered_flights = flights[
    (flights['origin'].isin(['JFK', 'EWR'])) &
    (flights['dest'] == 'SEA') &
    (flights['carrier'].isin(['UA', 'AA', 'DL'])) &
    (flights['month'] == 4) &
    (flights['day'].isin([1, 2, 3])) &
    (flights['sched_arr_time'] < 1200)
]


selected_columns = [
    'year', 'month', 'day', 'carrier', 'flight',
    'origin', 'dest', 'sched_dep_time', 'sched_arr_time'
]

result = filtered_flights[selected_columns].sort_values(by=['year', 'month', 'day', 'sched_arr_time'])

print(result)

        year  month  day carrier  flight origin dest  sched_dep_time  \
165210  2013      4    1      DL     183    JFK  SEA             745
166180  2013      4    2      DL     183    JFK  SEA             745
167168  2013      4    3      DL     183    JFK  SEA             745

        sched_arr_time
165210            1100
166180            1100
167168            1100